Deploy to prod, split configuration out of packaging, build once (back-propagated from top-tcp-java)

diff --git a/tcp-java-ecs/package-for-ecs b/tcp-java-ecs/package-for-ecs
--- a/tcp-java-ecs/package-for-ecs
+++ b/tcp-java-ecs/package-for-ecs
@@ -1,8 +1,10 @@
 #!/bin/bash
 
 # Create the Docker image for the service.
-# Label it with the first 7 chars of GIT_COMMIT and also with :latest
+# Takes one argument: the image repo (with no label).
+????# Label it with the first 7 chars of GIT_COMMIT and also with :latest
 # All actions are local to the VM; does not use aws or ecs-cli.
+# Should be run before configure-for-ecs and deploy-to-ecs are run.
 # Should be run before deploy-to-ecs is run.
 # Assumes the environemnt variable GIT_COMMIT is set (typically by Jenkins).
 # Assumes the directory for the service exists in this directory,
@@ -10,9 +12,8 @@
 
 # Fail on any error; unset variables are errors; show commands before executing:
 set -eux
-PROJECT="$1"
-ENV="$2"
-aws_region="$3"
+
+IMAGE_REPO="$1"
 
 GIT_COMMIT=${GIT_COMMIT:-unknown}
 GIT_COMMIT=${GIT_COMMIT:0:7}
@@ -24,11 +25,15 @@ ECS_DIR=$(find . -maxdepth 1 -type d -name "*-ecs")
 # TODO: make sure we're in the correct (root) directory
 # Can just check for Dockerfile, and cd .. if not there
 
+echo "=== package-for-ecs ==="
 date
 
 echo "Running in $PWD"
-echo "Project = $PROJECT"
-echo "Target Environment = $ENV"
+echo "IMAGE_REPO is $IMAGE_REPO"
+if [[ "$IMAGE_REPO" = "" ]] ; then
+    echo "ERROR: missing or empty image repository provided.  Quitting...."
+    exit 2;
+fi
 
 docker --version
 ls -al Docker* generate-keystore
@@ -51,33 +56,10 @@ EOF
 
 ./generate-keystore < gk-input && rm gk-input
 
-cp -p .env $ECS_DIR/
-
-# Add DB values to .env :
-DB_USER=$(aws ssm get-parameter --region $aws_region --name "/$PROJECT/$ENV/rds/username" --with-decryption --query "Parameter.Value" --out text)
-DB_PASSWORD=$(aws ssm get-parameter --region $aws_region --name "/$PROJECT/$ENV/rds/password" --with-decryption --query "Parameter.Value" --out text)
-DB_ENDPOINT=$(aws ssm get-parameter --region $aws_region --name "/$PROJECT/$ENV/rds/endpoint" --query "Parameter.Value" --out text)
-
-# Split at : into HOST and PORT:
-read DB_HOST DB_PORT <<<$(IFS=":"; echo $DB_ENDPOINT)
-
-# Note: do NOT use double-quotes around the values; bash isn't interpreting .env: ecs-cli compose is, and it does not drop quotes.
-cat >> $ECS_DIR/.env <<EOF
-DB_HOST=${DB_HOST}
-DB_PORT=${DB_PORT}
-DB_USER=${DB_USER}
-DB_PASSWORD=${DB_PASSWORD}
-AWS_REGION=${aws_region}
+echo "Adding IMAGE_REPO to .env file..."
+cat <<EOF >> .env
+IMAGE_REPO=$IMAGE_REPO
 EOF
-
-# Get the name ("repository" in Docker lingo) of the image from the doacker-compose.yml file:
-grep "image: .*amazonaws.com/" $ECS_DIR/docker-compose.yml
-IMAGE_REPO=$(grep "image: .*amazonaws.com/" $ECS_DIR/docker-compose.yml | sed "s/^[^\/]*\///")
-echo "Image repository from $ECS_DIR/docker-compose.yml is $IMAGE_REPO"
-if [[ "$IMAGE_REPO" = "" ]] ; then
-    echo "ERROR: missing or empty image repository in $ECS_DIR/docker-compose.yml .  Quitting...."
-    exit 2;
-fi
 
 echo "git commit hash is $GIT_COMMIT"
 mkdir -p src/assets/img
