Use git commit hash to tag images… (#81)
* Use first 7 characters of git commit hash (GIT_COMMIT env var) to tag images,
  also put git log -1 into src/main/resources/commit,
  rename variable IMAGE to IMAGE_REPO for accuracy,
  package-for-ecs: Use ECS_DIR

diff --git a/tcp-java-ecs/package-for-ecs b/tcp-java-ecs/package-for-ecs
--- a/tcp-java-ecs/package-for-ecs
+++ b/tcp-java-ecs/package-for-ecs
@@ -1,14 +1,23 @@
 #!/bin/bash
 
-# Create the Docker image for the tcp-java service.
+# Create the Docker image for the service.
+# Label it with the first 7 chars of GIT_COMMIT and also with :latest
 # All actions are local to the VM; does not use aws or ecs-cli.
 # Should be run before deploy-to-ecs is run.
+# Assumes the environemnt variable GIT_COMMIT is set (typically by Jenkins).
+# Assumes the directory for the service exists in this directory,
+# its name matches "*-ecs", and it is the only directory that matches.
 
 # Fail on any error; unset variables are errors; show commands before executing:
 set -eux
 PROJECT="$1"
 ENV="$2"
 aws_region="$3"
+
+GIT_COMMIT=${GIT_COMMIT:-unknown}
+GIT_COMMIT=${GIT_COMMIT:0:7}
+
+ECS_DIR=$(find . -maxdepth 1 -type d -name "*-ecs")
 
 # TODO: see if logging anything from this script would be helpful
 
@@ -42,7 +51,7 @@ EOF
 
 ./generate-keystore < gk-input && rm gk-input
 
-cp -p .env tcp-java-ecs/
+cp -p .env $ECS_DIR/
 
 # Add DB values to .env :
 DB_USER=$(aws ssm get-parameter --region $aws_region --name "/$PROJECT/$ENV/rds/username" --with-decryption --query "Parameter.Value" --out text)
@@ -53,7 +62,7 @@ DB_ENDPOINT=$(aws ssm get-parameter --region $aws_region --name "/$PROJECT/$ENV/
 read DB_HOST DB_PORT <<<$(IFS=":"; echo $DB_ENDPOINT)
 
 # Note: do NOT use double-quotes around the values; bash isn't interpreting .env: ecs-cli compose is, and it does not drop quotes.
-cat >> tcp-java-ecs/.env <<EOF
+cat >> $ECS_DIR/.env <<EOF
 DB_HOST=${DB_HOST}
 DB_PORT=${DB_PORT}
 DB_USER=${DB_USER}
@@ -61,9 +70,27 @@ DB_PASSWORD=${DB_PASSWORD}
 AWS_REGION=${aws_region}
 EOF
 
-echo "Building the tcp-java-api Docker image..."
+# Get the name ("repository" in Docker lingo) of the image from the doacker-compose.yml file:
+grep "image: .*amazonaws.com/" $ECS_DIR/docker-compose.yml
+IMAGE_REPO=$(grep "image: .*amazonaws.com/" $ECS_DIR/docker-compose.yml | sed "s/^[^\/]*\///")
+echo "Image repository from $ECS_DIR/docker-compose.yml is $IMAGE_REPO"
+if [[ "$IMAGE_REPO" = "" ]] ; then
+    echo "ERROR: missing or empty image repository in $ECS_DIR/docker-compose.yml .  Quitting...."
+    exit 2;
+fi
+
+echo "git commit hash is $GIT_COMMIT"
+mkdir -p src/assets/img
+git log -1 > src/main/resources/commit
+
+echo "Building the $IMAGE_REPO Docker image..."
 # TODO: may need sudo, or to run this script as sudo?
-docker build -t tcp-java-api:latest . -f tcp-java-ecs/Dockerfile
+docker build -t $IMAGE_REPO:$GIT_COMMIT . -f $ECS_DIR/Dockerfile
+# deploy script will look for $IMAGE_REPO:$GIT_COMMIT *and* $IMAGE_REPO:latest
+# TODO: should we even be tagging it "latest" yet?
+docker tag $IMAGE_REPO:$GIT_COMMIT $IMAGE_REPO:latest
 
 echo "Checking for the Docker image..."
-docker image ls | grep tcp-java-api
+docker image ls | grep $IMAGE_REPO
+
+date
